### ISSUE TITLE
매물 검색 범위 이슈

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#11]
초기 구상 단계에서는 지역을 안 가리고 크롤링 해서 매물을 보여주는 방식을 구상했습니다.
다만 이렇게 했을 때 두 가지 문제가 예상됩니다.
- 너무 많은 매물이 검색됨. (특히 직거래를 주로 하는 사람에겐 다른 지역의 매물이 불필요함)
- 일부 앱 에서는 GPS를 통한 동네 인증이 없으면 거래 자체가 안되게 돼있음.

이에 사용자 입장에선 필터를 여러 번 써서  불필요한 매물을 거르거나 오랜 시간을 들여 찾는 상황이 자주 생길 것 같아 해결책이 필요 해보입니다.

**Comment by stoneTiger0912** [comment]
크롤링 할때 지역범위로 나누겠습니다.

**Comment by kiw331** [comment]
그러면 서버단에서 지역에 따라 필터링을 할 수 있도록 사용자가 설정 탭에 지역정보를 미리 입력하고 검색할 때 상품이름, 필터단어와 함께 전송되도록 하겠습니다.
