### ISSUE TITLE
멘토링을 반영한 기능 변경 및 추가사항 의논

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#13]

**Comment by stoneTiger0912** [comment]
1.신뢰성 확보를 위한 방법

**Comment by kiw331** [comment]
당근 마켓의 매너온도와 같은 정보를 추가로 크롤링해오면 어떨까요

**Comment by jinbong-yeom** [comment]
> 당근 마켓의 매너온도와 같은 정보를 추가로 크롤링해오면 어떨까요

그런 정보가 없는 마켓도 있어서 매너온도로 식별하는 것은 어려울 것 같습니다.

**Comment by kiw331** [comment]
그런 방식이 아니면 크롤링 해오는 정보가 한정적이라   
저희 앱안에 신뢰성을 추가로 확보하기는 어려운거 같습니다.

**Comment by kiw331** [comment]
매너 온도가 아니더라도 다른 중고거래앱에서도 사기조회(중고나라앱)와 같은 기능을 제공하고 있습니다.
저희 어플의 역할이 다른 앱의 매물을 중계만 하는 역할이라 생각하면 추가적인 신뢰성 확보방법이 꼭 필요하다고 생각하지 않습니다.

**Comment by stoneTiger0912** [comment]
그러면 우선 신뢰성 확보방법에 대해선 넘어가도록 하겠습니다.

**Comment by stoneTiger0912** [comment]
2.  서버는 어떤 방식으로 할까요?

**Comment by kiw331** [comment]
서비스 특성 상 
상시로 열어놔야하고 다수의 트래픽 처리에 유리한 서버가 필요한거 같습니다.

**Comment by jinbong-yeom** [comment]
그럼 멘토님 의견을 받은 클라우드 서버를 사용하겠습니다.

**Comment by stoneTiger0912** [comment]
3.개발에 용이한 위한 요구 사항 정의서 작성
