### ISSUE TITLE
모니터링이 작동될 때 알림이 오는 조건

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#14]
초기 구상에선 기존 검색된 매물보다 낮은 상품이 새로 크롤링 되었을 때만 알림이 오도록 하였고
3주차 ppt에서도 모니터링-알림 기능에서 최저가가 갱신 되었을 때 알림이 오는 예상 결과물을 소개했습니다. 
다만 사람들이 매물을 찾을 때, 정확한 제품이름, 모델명을 정확하게 검색하긴 보단 '노트북'과 같이 제품군 하나를 검색하는 경우가 있습니다. 이럴 경우엔 검색해서 나오는 매물의 스펙이 다르기 때문에  최저가를 통해 알림을 받는 기능이 의미가 없어지게 될 것입니다.
또한 악세서리와 같은 부속품들이 물품이 같이 검색되는 경우가 있을 수 있고, 이럴 경우에도 현재 최저가가 지나차게 낮아지게 되어 알림 기능이 비정상적으로 작동하게 될 것 입니다.

위 상황을 고려한 알림이 오는 조건을 변경할 필요가 있어 보이는데 이에 대한 의견 내주세요.

**Comment by jinbong-yeom** [comment]
노트북이 어떤게 있는지 알아보기 위해 검색을 노트북이라는 워딩을 사용할 수는 있지만 제가 생각한 알림의 용도는 검색을 통해서 자신이 원하는 노트북 제품을 찾았을 시 혹은 구매자가 원하는 세부적인 제품에 대한 판단이 섰을때 정확한 제품명, 혹은 정확한 조건을 통해서 필터를 설정하고 찾는 제품의 최저가 알림을 받음으로서 최대한의 이익을 보장해 주는 것입니다. 부속품이 검색되는 문제는 필터기능을 통해서 개선의 여지가 있다고 생각되고 일단 먼저 해볼만한 가치는 충분히 있다고 생각합니다.

**Comment by stoneTiger0912** [comment]
그럼 나중에 회의해서 조금더 생각해보죠

**Comment by stoneTiger0912** [comment]
회의 해본 결과 가격범위로 알림을 설정 하는 것이 좋을 것 같습니다.
