### ISSUE TITLE
필터링을 어떤 방식으로 할까요?

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#15]
필터링을 하는 방식을 구체적으로 정합시다

**Comment by stoneTiger0912** [comment]
일단 상세 페이지에 원하는 단어가 있는 매물만 출력하는건 어떤가요

**Comment by kiw331** [comment]
등록된 상품들을 보면 상품설명(상세페이지)를 길게 작성해 놓은 상품들이 많습니다. 상세 페이지에서 까지 필터링을 하면 필터링 시간이 오래 걸리고 필요 이상으로 많은 상품들이 걸러지게 될 꺼 같습니다.
키워드가 제목에 들어간 매물 중에 필터링 단어를 제외한 상품을 출력하는 식이 더 나아 보이네요

**Comment by stoneTiger0912** [comment]
그럼 제목으로 하겠습니다.
