### ISSUE TITLE
매물 페이지 이동

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#16]
한 화면에서 볼수있는 매물을 다 보고 다음 매물로 넘어갈때 어떻게 하면 좋을까요.

**Comment by stoneTiger0912** [comment]
페이지네이션으로 하는건 어떤가요?

**Comment by kiw331** [comment]
페이지네이션으로 페이지를 구분하거나
무한스크롤 방식을 생각하고 있습니다.

**Comment by kiw331** [comment]
RecyclerView로 구현 후 테스트 완료 했습니다
