### ISSUE TITLE
데이터베이스의 데이터 지우는 시점

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#17]
크롤링한 데이터를 데이터베이스에 저장한다음 작업 수행후 지우는 시점을 언제로 하면 좋을까요?

**Comment by kiw331** [comment]
일반적으로 생각하면 사용자가 알림기능을 해제했을때 (사용자가 키워드에 해당하는 상품을 구했거나 더 이상 찾지 않을때) 크롤링한 정보를 DB에서 삭제하는게 맞는 방향이겠으나 DB에 이전 키워드에 관한정보를 남겨놔서 따로 활용할 수 있는 여지가 있을지는 생각해볼 문제인거 같습니다
ex) 조회했던 상품 기록 보기

**Comment by jinbong-yeom** [comment]
전체 데이터를 DB에 저장하고 필터링하여 가져오는 방식으로 변경되었습니다.

**Comment by jinbong-yeom** [comment]
기존 데이터 베이스와 크롤링한 데이터를 비교하여 크롤링한 데이터에 데이터베이스의 데이터가 없다면 이미 물건이 팔린 것 으로 간주하고 데이터베이스에서 해당 데이터를 삭제하겠습니다.
