### ISSUE TITLE
중간발표-Problem

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#18]
중간 발표 자료를 준비하다 논의할 점이 생긴거 같습니다.
3주차 발표 때는 input output을 기존 어플들의 정보, 통합된 매물의 정보라고 설명하였으나
사용자 입장에서 전체 앱서비스의 입력과 출력은 '사용자의 검색어', '통합된 매물정보'가 오히려 적절할거 같은데 어떻게 생각하시나요

**Comment by jinbong-yeom** [comment]
그럼 input을 상품키워드와 필터링 키워드, output을 통합된 상품 리스트와 갱신된 상품 알림으로 하는 것이 좋을 것 같습니다.

**Comment by kiw331** [comment]
9주차 수업에서 교수님이 problem 관점에서 입출력을 결정하는게 맞다고 언급하셨습니다.
INPUT을 		상품키워드와 필터링 키워드
OUTPUT을 	통합된 상품 리스트와 갱신된 상품 알림으로 정하고 결과보고서 등 제출물에도 통일하여 반영하겠습니다.

**Comment by kiw331** [comment]
다만, 통합된 상품리스트는 현재 크롤링할 항목에 갱신시간이 들어갈지 논의 중 이기 때문에 정확히 정해지면  
상품출력되는 형태를 이미지로 첨부해서 Problem파트를 부연 설명하면 좋을거 같습니다.
