### ISSUE TITLE
서비스 기대효과 및 발전방향

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#19]
최종 결과 보고서에 적힐 우리 서비스의 기대효과와 발전방향에 대해서 의견 남겨주세요.

**Comment by jinbong-yeom** [comment]
현재 3가지의 마켓만을 통합하지만 추후에 더 통합할 수 있는 확장성이 발전 방향일 것입니다.
또 우리 서비스가 대중화 되어 영향력이 커진다면 지금은 중고거래어플별로 각기 다른 신뢰성 확보정책을 통일할 수 있을 것입니다.

**Comment by stoneTiger0912** [comment]
저희의 어플은 모니터링을 통한 알람기능을 이용하여 중간중간에 확인하지않고 원하는 매물이 뜰경우 자동으로 알림을 줘서 모니터링 하는동안 검색하는 시간을 줄이는 기대효과가 있을 것입니다.

**Comment by kiw331** [comment]
Problem에서 언급한데로 중고거래 시장 규모가 점점 커지고 있는 지금, 중고 거래 상품을 검색하고 알림을 받는 시간을 줄일 수 있다는게 가장 큰 기대효과라고 할 수 있을거 같습니다
