### ISSUE TITLE
2차멘토링질문할것

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#20]

**Comment by jinbong-yeom** [comment]
데이터베이스에 있는 데이터를 지우는 방식과 시점에 대해서 질문.
검색마다 불러오고 모니터링후 지울지 OR
미리 불러놓고 모니터링으로 계속 업데이트식 db에서 가져다 씀
지우는 시점은 고민중

**Comment by kiw331** [comment]
결과 보고서 내용에 관한 피드백
(발표자료 업로드 예정입니다)

**Comment by kiw331** [comment]
처음 질문과 연계 해서
원래 검색/알림 모두 사용자 입력→크롤러가 상품정보 수집→DB에 저장→어플에서 데이터 출력 순으로 구상을 했으나
단순히 검색 내용을 출력만 하기 위해서 데이터를 DB에 넣는 과정은 시간만 들고 불필요 하다는 논의가 있었습니다.
검색 동작 시에 DB에하는 단계를 건너뛰는 방안에 대한 생각을 여쭤보면 좋을 것 같습니다.

**Comment by kiw331** [comment]
보안 요구사항에 관한 질문
•실무에서 injection 공격 등을 어떻게 대비하는지

•우리 서비스 특성상 한번의 입력에 클로러부터 시작하여 여러단계의 동작이 일어나는데 
디도스 공격 등으로 발생하는 서버과부하를 방지할 수 있는 방법
(같은 사용자로 부터 입력 시간을 제한하는 방안 등을 생각중)

**Comment by stoneTiger0912** [comment]
통신 방법으로는 어떤 것들을 사용할 수 있을까요?
