### ISSUE TITLE
통신방법 정하기

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#21]
제 생각에는 가장 무난한 rest api방식으로 할까 생각하는데 다른 의견 있으시면 코멘트 남겨주세요

**Comment by kiw331** [comment]
rest api방식 중 비교적 최근에 구현된 Retrofit라이브러리가 편리하고 합니다.

**Comment by jinbong-yeom** [comment]
NCP클라우드 서버를 사용하게 됬는데 여기서의 통신을 rest api로 하신다는 거죠?

**Comment by stoneTiger0912** [comment]
네 그렇습니다.

**Comment by jinbong-yeom** [comment]
알겟습니다. 체택하는게 좋겠네요

**Comment by stoneTiger0912** [comment]
그럼 rest api 방식 중 Retorfit라이브러리를 사용하겠습니다.
