### ISSUE TITLE
unimarkert.py 8번째 줄에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#23]
from pymongo import MongoClient
client=MongoClient(host='localhost',port=27017)
print(client.list_database_names())
db=client['UniMarketDB']
collection=db['data']
posts=db.data
db.list_collection_names()
import pprint
for i in posts:
      pprint.pprint(i.find_one())
여기서 TypeError: 'Collection' object is not iterable가 나는데 

from pymongo import MongoClient
client=MongoClient(host='localhost',port=27017)
db=client['UniMarketDB']
collection=db['data']
posts=db.data
for i in posts.find():
      print(i)
이렇게 바꾸면 에러가 고친것을 확인하였습니다.

**Comment by jinbong-yeom** [comment]
수정사항 확인하고 반영했습니다.

**Comment by stoneTiger0912** [comment]
확인했습니다.
