### ISSUE TITLE
서버 환경 바꾸기

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#24]
기존에 서버를 aws환경에서 하기로 했는데 사용에 문제가 있어서 NCP환경에서 진행 하려합니다. 괜찮을까요?

**Comment by stoneTiger0912** [comment]
되면 둘중에 어느것을 사용해도 상관없을 것 같습니다.

**Comment by kiw331** [comment]
한국인 입장에선 접근성 면에서 오히려 좋을 거 같습니다 
결과 보고서에 시스템 구성도 수정하고 발표 자료에도 반영하겠습니다.

**Comment by jinbong-yeom** [comment]
네 그럼 NCP환경으로 진행하겠습니다.
