### ISSUE TITLE
가격을 나타내는 방법을 어떻게 할까요?

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#25]
중고거래 특성상 개인이 올리기때문에 00만원, 1000, 1,000원 이렇게 다 다릅니다. 이것을 통합하려고합니다.
00만원 이나 1,00,000원 으로 표현할까 하는데
저는 후자가 좀 쉽게 표현할 수 있을 것같아서 후자를 하는게 편하다고 하는데 의견부탁합니다.

**Comment by kiw331** [comment]
만원 단위로 표시하는게 보기 편하지 않을까요

**Comment by jinbong-yeom** [comment]
흠, 근데 파이썬 자체에서 지원하는 함수가 있다고 하니 편의상 일단 뒤에 것 으로 구현 하는것도 나쁘지 않을 것 같네요

**Comment by stoneTiger0912** [comment]
그럼 3자리 수마다 콤마를 사용하는 것으로 하겠습니다.
