### ISSUE TITLE
11주차 회의록

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#26]
11/13(일) 14:00~19:00 회의 내용 정리입니다
현재까지 진행상황과 변경점, 앞으로 계획에 대해 간략히 공유해주세요

**Comment by jinbong-yeom** [comment]
AWS >NCP환경으로 변경하게 되었습니다.

**Comment by jinbong-yeom** [comment]
NCP서버에 micro 서버 생성하였습니다.

**Comment by stoneTiger0912** [comment]
DB 출력 에러를 수정하였습니다.

**Comment by stoneTiger0912** [comment]
추가 필터링과 제외 필터링을 추가하였습니다.

**Comment by jinbong-yeom** [comment]
stoneTiger0912 수정사항 반영했습니다.

**Comment by kiw331** [comment]
어플:
- 지역 설정 기본 입력 인터페이스 구현
- 검색 탭에서 키워드 입력 구현
- 임시 서버로 입력값과 지역 전송 (rest api 테스트)
