### ISSUE TITLE
개인정보 법적 문제 이슈

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#28]
멘토님이 말씀 해주신 중고거래에 사용되는 사용자의 개인정보를 가져오는 것에 대한 법적 문제에 대해서 생각해봅시다.

**Comment by stoneTiger0912** [comment]
저희가 가져오는 것은 사용자의 개인정보가 아닌 것 같습니다.

**Comment by jinbong-yeom** [comment]
정보에 개인정보가 있어도 개인정보를 제외한 정보만을 가져와야 하겠습니다.
