### ISSUE TITLE
보안면에서 Injection방어방법 

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#29]
멘토님께서 Injection방어방법에 대해 정리한 사이트를 주셨습니다.
http://blog.plura.io/?p=6056

<img width="858" alt="image" src="https://user-images.githubusercontent.com/91014308/201508284-602b361e-e209-4de1-a8c4-01093863e8ce.png">

**Comment by kiw331** [comment]
```
2) 저장 프로시저는 사용하자고 하는 Query 에 미리 형식을 지정하는 것을 말합니다. 지정된 형식의 데이터가 아니면 Query 가 실행되지 않기 때문에 보안성을 크게 향상시킵니다.
```
에 관한 내용은 검색 키워드로 입력될 수 있는 값이 너무 많기 때문에 적용하기 힘들꺼 같습니다.

**Comment by jinbong-yeom** [comment]
![image](https://user-images.githubusercontent.com/85209577/201508620-9018a4c9-867d-43b9-8b74-c7266056fdda.png)
에 관한 내용은 개발 여건상 일부만 적용할 수 있을 것 같습니다.

**Comment by stoneTiger0912** [comment]
그러면 1번과 3번의 일부분을 적용하는것으로 하겠습니다.
