### ISSUE TITLE
4주차 멘토링 질문정하기

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#3]
4주차 멘토링 때 질문할 사항 의견 내주세요.

**Comment by kiw331** [comment]
앱서비스를 위한 서버 추천

**Comment by jinbong-yeom** [comment]
팀에서 생각한 모니터링 기반 서비스 방법으로 얼마나 많은 유저가 참여할 수 있을까요?
혹시 많은 인원이 사용하는데 문제가 있다면 해결방안은 무었이 있을까요?

**Comment by stoneTiger0912** [comment]
3.알림을 주기위해서는 회원가입, 로그인을 만들어서 알림을 줘야할까요?

**Comment by jinbong-yeom** [comment]
4. 팀원이 나누어서 개발을 하고 합병을 하는 방식으로 개발을 해야만 하는데 
우리 시스템을 어떤 식으로 나누어서 개발해야 할까요?

**Comment by stoneTiger0912** [comment]
5. 필터 방식을 태그형식으로 하는 경우에 문제점같은게 있을까요? 아니면 다른 방식을 사용하는게 나을까요?

**Comment by kiw331** [comment]
1,2 번은 의미가 다소 겹치는 것 같아 '다수의 사용자를 고려한 서버 구축 방법' 와 같이 통일 하겠습니다.
그 외 나머지 내용도 포함해서 텍스트 파일로 정리하고 공유드리겠습니다.
