### ISSUE TITLE
추후에 크롤링이 막힐 경우

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#30]
멘토님이 말씀해주신, '지금은 중고거래 플랫폼들이 크롤링이 허용되어 있지만 나중에는 클롤링을 막을수도 있다. 그에 대해서 해결방안을 생각해보라'에 대해서 생각해봅시다.

**Comment by stoneTiger0912** [comment]
추후에 막힐경우 저희가 직접 중고거래 플랫폼이 되는것도 좋을 것 같습니다.

**Comment by jinbong-yeom** [comment]
크롤링이 막힌다면 해당 사이트와 비지니스적인 계약을 맺는 방법도 있을 것 같습니다.
