### ISSUE TITLE
상품 상세 페이지 크롤링 시점 

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#31]
원래는 처음부터 상세 페이지의 텍스트까지 크롤링 하여 저장하는 방식을 생각했으나 이럴 경우에 크롤링 시간이 문제가 되는걸 확인 했습니다.
상세 페이지 텍스트를 크롤링하는 시점을 변경 하는게 필요해보입니다.

**Comment by stoneTiger0912** [comment]
그럼 상세페이지를 크롤링 하지 않는 것이 어떤가요?

**Comment by jinbong-yeom** [comment]
클릭할 때 크롤링하는게 어떨까요? 하나만 하기때문에 시간이 적게 소요될 것 같습니다.

**Comment by kiw331** [comment]
그럼 일단 초기에 상세페이지를 제외 항목을 크롤링 하는 것으로 바꾸고
상품 페이지를 눌렀을 때 링크를 통해 바로 이동하는 방식을 먼저 해보고 
이후 여력이되면 출력 되는 상품을 눌렀을 때 해당하는 상품의 상세 페이지와 링크를 크롤링하여 보여주는 식으로 구현하겠습니다.
