### ISSUE TITLE
지역을 안적은 매물에 대한 저장이슈 

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#32]
<img width="858" alt="스크린샷 2022-11-13 오후 3 41 01" src="https://user-images.githubusercontent.com/91014308/201509298-9e549845-d771-45cf-847a-2478ee296c6a.png">
지역을 안적은 매물이 존재하는데 어떻게 하는 것이 좋을까요?

**Comment by jinbong-yeom** [comment]
신뢰성측면을 고려하면 걸러주는게 좋을 것 같습니다.

**Comment by kiw331** [comment]
저희가 직거래를 주 타겟으로한 서비스를 목표로 하고 있으므로 지역이 안보이는 매물을 우선 출력하지 않아도 될꺼같습니다

**Comment by stoneTiger0912** [comment]
그럼 일단 신뢰성을 위해 안적은 것은 출력하지 않겠습니다.
