### ISSUE TITLE
라이선스 정하기

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#33]
저희 서비스가에서 명시할 라이선스를 고릅시다

**Comment by kiw331** [comment]
https://www.olis.or.kr/license/compareGuide.do

라이선스 비교표를 참고하면 되겠습니다

**Comment by jinbong-yeom** [comment]
많이 사용하는 Apache License 2.0를 사용하는 건 어떨까요?

**Comment by stoneTiger0912** [comment]
비교적 조건이 느슨한 mit라이선스는 어떤가요?

**Comment by kiw331** [comment]
MIT라이선스로 결정하고 README파일 업데이트 하겠습니다
