### ISSUE TITLE
UI 개선 방안

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#35]
멘토링을 통해 피드백 받은거 처럼 접근성있고 친근감이 드는 UI가 중요할거 같습니다.
현재 구상한 UI를 보고 개선의견을 내주세요
![화면2](https://user-images.githubusercontent.com/100690081/201509865-b0c57b0f-facf-4699-a28a-814adebaa701.png)

**Comment by stoneTiger0912** [comment]
폰트를 추가하면 기존 글씨체보다 나을것 같습니다.

**Comment by kiw331** [comment]
- 폰트추가 완료: 주아체

**Comment by kiw331** [comment]
필터 키워드/가격 범위를 다른 레이아웃에서 설정하고 검색 탭에는 검색화면과 판매 상품만 출력하는게 깔끔해보임.

**Comment by kiw331** [comment]
![image](https://user-images.githubusercontent.com/100690081/205504539-af4855bc-39f9-4aef-b5ae-dee35bdce493.png)

**Comment by jinbong-yeom** [comment]
설정화면에 다른기능을 하나더 추가하는 것이 좋아보입니다.

**Comment by kiw331** [comment]
구현 해봤을 때도 설정 탭에 빈 공간이 너무 많아 보였던거 같습니다.
장애 발생 리포트 #38 정했던거 처럼, 설정 탭에 개발자에게 메일 보내는 UI를 함께 구성하겠습니다.
