### ISSUE TITLE
광고성 상품 거르기

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#36]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/91014308/201511067-01cdc942-1f09-4ad0-9b77-8771e389e5f2.png">
이런것 같이 광고성 상품이 있는데 어떻게 할까요?

**Comment by kiw331** [comment]
올라오는 광고성 상품을 보면 불필요한게 너무 많이 포함된거 같습니다.
디폴트로 서버단에서 광고성 상품이 출력 안되게 하는게 어떨까요

**Comment by jinbong-yeom** [comment]
광고성 상품으로 여겨질 수 있는 상품에 대한 키워드를 미리 설정해서 크롤링이 안되도록 하는 것이 좋을 것 같습니다.

**Comment by kiw331** [comment]
여력이 된다면 사용자 설정에 광고성 상품 필터를 선택할 수 있는 체크 박스를 추가하면 좋을거 같습니다

**Comment by stoneTiger0912** [comment]
체크박스 추가는 나중에 논의하기로 하고 상품에 대한 키워드를 미리 만들어나서 필터링 하도록 하겠습니다.
