### ISSUE TITLE
최종적으로 크롤링해서 얻어오는 정보항목들을 정합시다.

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#37]
최종적으로 크롤링해서 얻어와서 DB에 저장할 정보항목들을 정합시다.

**Comment by stoneTiger0912** [comment]
Item_id, title, picture, region, price, link를 할예정입니다.

**Comment by jinbong-yeom** [comment]
추가적으로 각 중고거래마켓의 이름도 가져오는 것이 좋겠습니다.

**Comment by stoneTiger0912** [comment]
네 추가 하겠습니다.
