### ISSUE TITLE
장애 발생 리포트

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#38]
저희가 요구사항 정의서에 명시한대로 장애 발생시 복구할 수 있는 방법이 필요한거 같습니다. 
우선 장애 발생에 대한 알림을 받을 수 있는 방법이 무엇이 있을까요

**Comment by kiw331** [comment]
설정/마이페이지 탭에 버그리포트를 할수 있는 인터페이스를 만들고 개발자 이메일을 연결 해놓으면 좋을거 같습니다

**Comment by jinbong-yeom** [comment]
설정/마이페이지 탭에 버그리포트를 할수 있는 인터페이스를 만들고 개발자 이메일을 연결 해놓으면 좋을거 같습니다

**Comment by kiw331** [comment]
0cbff35b3830e7ce83573aaa3de8a1f285d49ce8
