### ISSUE TITLE
발명 설명서에 넣을 논문들 찾아봅시다.

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#39]
http://kpat.kipris.or.kr/kpat/biblioa.do?method=biblioFrame&start=biblio&searchFg=N&KeyWord=1020150079387&applno=1020150079387&Gubun=1&sCurrPage=1&searchFg=N&expression=1020150079387&openPageId=View01&isMyConcern=N&isMyFolder=N&config=/main/sharePage_KR.jsp,%20className=jeus_jspwork._main._700_sharePage_5fKR_5fjsp,%20jspUri=%27/main/sharePage_KR.jsp
저는 이거 찾았는데 어떤가요?

**Comment by jinbong-yeom** [comment]
[보안성 증대를 위한 중고거래 모바일 플랫폼 서비스 디자인 제안](https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=JAKO202123157261841&dbt=NART) 찾았습니다.

**Comment by kiw331** [comment]
빅데이터 기반 홈 중고 가전 거래 플랫폼 시스템
https://patents.google.com/patent/KR102149383B1/ko

가전 품목에 한정한 중거거래 플랫폼입니다

**Comment by stoneTiger0912** [comment]
그럼 위의 3개를 취합하여 정리할게요
