### ISSUE TITLE
개발 역할 분담

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#4]
서버, 앱, 크롤링 3가지를 각각 누가 맡았으면 좋겠는지 의견을 남겨 주세요.

**Comment by kiw331** [comment]
제가 짧지만 어플 개발 경험이 있습니다.
앱 파트 맡겠습니다.

**Comment by stoneTiger0912** [comment]
저는 서버, 클로링 가능합니다.

**Comment by jinbong-yeom** [comment]
저는 다 비슷한 수준인데 서버 맡는게 나을 것 같습니다.

**Comment by stoneTiger0912** [comment]
그럼 제가 크롤링 할까요?

**Comment by jinbong-yeom** [comment]
그럼 stoneTiger님이 크롤링 맡으시고 제가 서버 맡고 kiw님이 어플 개발로 하겠습니다.
