### ISSUE TITLE
발명설명서에 적을 발명의 효과논의

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#40]
발명의 효과란에 어떤 내용이 적혀지면 좋을지 남겨주세요

**Comment by jinbong-yeom** [comment]
"사용자가 상품을 찾는 시간을 크게 절약할 수 있다." 있습니다

**Comment by kiw331** [comment]
모니터링을 통한 알림 기능의 효과를 언급하면 좋을 것 같습니다.
발명의 배경에서 언급한 중고거래 환경에서 문제점을 일부 해소할 수 있을 것입니다.
