### ISSUE TITLE
크롤링 관련해서 변경하는게 좋겠다고생각합니다.

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#41]
처음에 저희 크롤링은 키워드 부분만 크롤링하려고 생각하였는데 기술적인 문제로 최신 제품들을 모두 크롤링을 하여서 DB에 저장하고 그 후에 원하는 키워드를 DB에서 찾아 출력하는 것으로 바꾸는게 나을 것 같습니다.

**Comment by jinbong-yeom** [comment]
알겠습니다.

**Comment by kiw331** [comment]
검색 전에 DB에 정보를 취합해 두면 검색 시간을 줄이는 효과가 있을꺼 같습니다.

**Comment by stoneTiger0912** [comment]
그럼 그렇게 하는걸로 하겠습니다.
