### ISSUE TITLE
11.26 회의록

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#42]

**Comment by jinbong-yeom** [comment]
공인 ip문제로 아마존으로 돌아가야 할 수도 있겠습니다. 유료 서비스네요. NCP에서는....

**Comment by stoneTiger0912** [comment]
그럼 유료 서비스를 하죠 얼마나 하나요?

**Comment by jinbong-yeom** [comment]
4000원 정도인데 제가 결제 하겠습니다. 아마존으로 다시 가기엔 늦은거 같군요.

**Comment by kiw331** [comment]
• 발명설명서 수정
-플로우 차트 설명 보안 
-청구항 수정: 크롤링을 통한 중고거래 상품 통합 삭제

**Comment by kiw331** [comment]
• 크롤링 방식 변경
'검색 -> 크롤러 작동 ...' 크롤러가 상시로 DB에 투플을 추가하고 
사용자가 상품 검색 시 미리 저장된 정보를 받아오는 방식으로 채택하기로 함

**Comment by kiw331** [comment]
• Peer-review 반영 사항
판매자의 평가 제공(당근 마켓: 매너온도, 번개장태: 평점, 거래내역) 등의 추가 정보 받아오기
-DB에서 정보를 불러오는 방식으로 검색 시간도 줄어들어 추가 정보를 가져 오는게 가능해 보임

**Comment by stoneTiger0912** [comment]
• 크롤링 방식 변경
'검색 -> 크롤러 작동 ...' 크롤러가 상시로 DB에 투플을 추가하고
사용자가 상품 검색 시 미리 저장된 정보를 받아오는 방식으로 채택하기로 함
