### ISSUE TITLE
Peer-review 반영사항

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#43]
12주차  Peer-review 수업 후 comment를 10개 전달 받았습니다
.
▶Problem
1)'거래 가능한 지역에 사용자가 원하는 상품이 바로 없을 경우가 많고'라고 문제점을 지적하는 부분에서 거래 가능한 지역으로 국한하는 이유가 무엇인지 명시해주세요.

2)중고 거래 사이트에서 데이터를 모을 때 크롤링을 허용하는 범위의 문제가 발생할 수 있을 것 같습니다.

3)사기 매물의 가격이 저렴하다는 특성을 생각하면 가격 필터링은 사기매물만 보여주는 결과를 도출할 수 있다고 생각합니다. 

▶Solution
4)등록된 매물을 검색하는 필터링에 대한 설명이 무엇을 필터링할 수 있는지 알려줬으면 좋겠습니다.

5)매물을 등록한 판매자의 평가도 제공하는 기능이 있으면 좋겠습니다. (예, 당근의 매너온도, 중고나라에서 표정 이모티콘을 이용한 평가)

6)중고거래 사이트에는 구매를 원하는 글도 올라오는 데 어떻게 처리하는지 제시해 주셨으면 합니다.

7)구매자가 어떤 한 종류의 물건만을 필요로 하는 것이 아니라면 알림에 범위 기능을 도입해서 그와 비슷한 성능을 가진 물건이 마켓에 등록되었을 때 알림이 오도록 설계해주는 것도 좋을 것 같습니다.

8)검색 결과만 보여주면 사기피해에 대해 책임을 질 일이 없을 것 같지만, 추후에 '서비스가 대중화되면 거래어플의 제품에 대한 신뢰 정책을 통일하여 보여준다'는 점이 중고나라에 올라온 판매물품에 대해 구매자가 거래하려 할 때 사기가 아니고 안전한 거래가 될 가능성에 대해 보여준다고 하는 것이라면 책임 소재를 떠안는 모양이 될 것 같습니다.

▶차별성 
9)상용제품 중 중고다검색은 어떠한 한계점이 있어서 정상적으로 운영되지 않는 것인지, 또 중고거래 앱 통합 서비스는 통합플랫폼으로써 어떠한 차이점이 있어 정상적으로 운영될 것으로 전망하는지에 대한 정보가 부족합니다.

10)카카오, 네이버와 같이 누구나 쉽게 접근할 수 있는 사이트에서 제공하는 중고 물품 검색 기능(예: 네이버쇼핑, 쇼핑하우)과 무엇이 다른지 명시해주세요.

코멘트 중에서 프로젝트에 반영할 사항을 정해봅시다.

**Comment by kiw331** [comment]
(1), (2), (3), (4), (6), (8), (9), (10) 은 단순히 내용을 추가하고 이에 대한 response를 작성 하면 될꺼 같습니다.

**Comment by jinbong-yeom** [comment]
7번은 질문은 어려울 것 같고 5번은 가능할 것 같습니다.

**Comment by kiw331** [comment]
(7)"비슷한 성능을 가진 물건"이라는 기준이 모호하여 처리하기 어려울 것으로 보이고 관련 서비스를 제공하는 중고거래 어플도 없는걸로 확인됩니다. 이 내용을 언급하여 response를 만들고 5번.판매자 정보는 여력이 되면 같이 반영해보는 방향으로 진행하겠습니다.
