### ISSUE TITLE
구글시트에 넣을 질문정하기

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#45]
저희 평가방법을 구글시트를 통한 정성평가로 정해졌는데 질문할 것들 적어주세요

**Comment by kiw331** [comment]
몇 가지 항목을 정하고 각 항목 별로 1~5점과 같이 점수를 받게하는건 어떨까요
어플의 보완점을 직관적으로 알 수 있을 거 같습니다

**Comment by stoneTiger0912** [comment]
검색이 제대로 출력되는가?
알람이 제대로 원하는 제품을 알려준다
일단 두가지 어떤가요?

**Comment by jinbong-yeom** [comment]
사용 편의성에 대해서도 점수로 받는것이 좋겠습니다.
자유롭게 의견있으면 남겨주세요. 항목도 추가하는게 좋을것 같습니다.

**Comment by kiw331** [comment]
UI와 디자인 평가

**Comment by stoneTiger0912** [comment]
추가적으로 14주차 수업에서 차별성에 대해서 언급하면 좋을 것 같습니다.

**Comment by stoneTiger0912** [comment]
위에 내용을 토대로 구글 시트를 만들겠습니다
