### ISSUE TITLE
서버로 부터알림을 받는 방식

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#46]
이전 이슈로 통신 방법을 REST API를 사용하기로 정했습니다.
여기서 알림 받는 동작에 대한 구체적인 방법을 정할 필요가 있어 보입니다.

현재 FIRE BASE, OneSignal 등이 검색되는데 어떤 방식을 사용하는게 좋을까요

**Comment by jinbong-yeom** [comment]
알림방식으로는 Fire base를 사용하는 것이 좋겠습니다.

**Comment by kiw331** [comment]
검색을 더 해보니 파이어베이스을 통한 푸쉬 알림이 주로 나와 있는거 같습니다.
검색 기능 완성되면 앱,서버단에서 각자  공부해서 구현하면 될꺼같습니다.
