### ISSUE TITLE
Final presentation 준비

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#48]
기말발표 ppt에 포함될 내용에 대한 의견 내주세요
앞 부분은 중간 발표와 구성이 같으니 일부 변경된 사항만 수정하면 되겠고
• 결과물 • Challenging issues 파트 위주로 토의 해보면 좋을 꺼같습니다.

**Comment by jinbong-yeom** [comment]
아직 평가방법을 정하지 않아서 정해야 할 것 같습니다.

**Comment by kiw331** [comment]
저희 어플이 성능을 나타낼 수 있는 명확한 지표가 나오는게 아니므로
설문지같은 정성평가 방법을 사용하는게 적절할꺼 같습니다

**Comment by kiw331** [comment]
### Solution
- 동작순서, 플로우차트 수정
   - 크롤링은 상시로 진행하고 입력됬을 때 DB에서 값 받아오는 방식으로
- 서비스 구성도-> 시스템 구성도로 변경
- 예상 화면은 결과물에서 보여주기

**Comment by kiw331** [comment]
### 한계점

- 카테코라이징 안됨
- 크롤링관련하여 정책/법 적인 문제

- 평가표에서 개선상항 받는거도 좋은생각같습니다

**Comment by jinbong-yeom** [comment]
한계점 
- 당장에 수익 창출이 어렵다.
- 크롤링 허용에 강하게 의존한다.
- 현재 필터링은 1가지만 지원한다.
