### ISSUE TITLE
프로젝트에 쓸 언어 정하기

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#5]
프로젝트에 쓸 언어를 정합시다

**Comment by stoneTiger0912** [comment]
크롤링은 파이썬이 예제가 많이 사용하기 쉬워서 크롤링의 경우 파이썬으로 짤예정입니다.

**Comment by kiw331** [comment]
안드로이드 스튜디오 상에서는 이미 다뤄본 경험이 있고 인터넷에 예제가 많이 나와있는 자바로 통일하는게 좋을거 같습니다.

**Comment by stoneTiger0912** [comment]
> 에 예제가 많이 나와있는 자바로 통일하는게 좋을거 같습니다.

동의합니다!

**Comment by jinbong-yeom** [comment]
> > 서버에서 쓸 언어로는 자바 기반 언어인 spring과 파이썬 기반 언어인 django를 생각하고 있는데 스프링은 확장성이 높고 많은 라이브러리를 지원하며 라이브러리를 떼어내기도 쉽다는 장점이 있고 장고는 효율을 중시하여 빠른 게발에 초점을 둔다는 장점이 있습니다. 두 언어중 고민입니다.....
> 
> 일단 장고가 빠르기도 하고 제가 크롤링을 파이썬으로 할 예정이기 때문에 파이썬으로 통합하는게 나을 것 같습니다.
> 


> > 서버에서 쓸 언어로는 자바 기반 언어인 spring과 파이썬 기반 언어인 django를 생각하고 있는데 스프링은 확장성이 높고 많은 라이브러리를 지원하며 라이브러리를 떼어내기도 쉽다는 장점이 있고 장고는 효율을 중시하여 빠른 게발에 초점을 둔다는 장점이 있습니다. 두 언어중 고민입니다.....
> 
> 일단 장고가 빠르기도 하고 제가 크롤링을 파이썬으로 할 예정이기 때문에 파이썬으로 통합하는게 나을 것 같습니다.

확실히 학기 안에 해야하는 프로젝트인만큼 파이썬으로 하는게 나을것 같네요. 알겠습니다.

**Comment by stoneTiger0912** [comment]
그럼 앱은 자바, 크롤링 및 서버는 파이썬으로 하는 것으로 픽스 합니다.
