### ISSUE TITLE
당근마켓에서 상세 설명부분에서 오류가 나네요

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#51]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/91014308/204994448-67e98365-1a56-4457-8077-93aa152055ce.png">

**Comment by stoneTiger0912** [comment]
다른건 안그러는데 당근마켓에서만 오류가 나네요

**Comment by stoneTiger0912** [comment]
상세설명이 없을경우 공백할까요?

**Comment by kiw331** [comment]
상세설명 비워져있어도 앱 단에서는 상세설명이 없는걸 확실히 알 수 있게 출력해주는게 좋을거 같습니다.
"상세 설명 없음" 문자열을 직접 넘겨주는거도 방법이 될거 같습니다.

**Comment by stoneTiger0912** [comment]
음 그럼 상세설명 없음으로 하겠습니다.
