### ISSUE TITLE
12.01 회의록

### ISSUE THREAD

**Issue by jinbong-yeom** [jinbong-yeom/Uni_Market#59]
12월 1일 회의록입니다.

**Comment by jinbong-yeom** [comment]
서버에서 데이터 필터링하여 읽어오는 작업 수행

**Comment by kiw331** [comment]
### 어플
* 인트로 구현
* SEARCHVIEW로 검색 창 구현
* 검색 버튼으로 submit되었을 때 서버에 키워드 전달(아직 json 완성된건 아님)


**다음에 할 꺼**
* 어플 폰트 정해서 적용 ( 나중에 하면 글자 자간 바뀌면서 어색해 보일 수 있으니까 되도록 빨리하는게 좋아보임)
* JSON 파일 형식 정하기
* 지역 추가 구현, JSON으로 함께 전송 테스트

**Comment by stoneTiger0912** [comment]
크롤링부분 마무리
가격 형식 변경
