### ISSUE TITLE
어플 아이콘 디자인 정하기

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#6]
유니마켓 어플 아이콘 디자인에 대한 아이디어 내주시면 감사하겠습니다.

**Comment by jinbong-yeom** [comment]
기존 마켓들을 통합한다는 인상이 드는 디자인이 좋을꺼 같습니다.

**Comment by kiw331** [comment]
안드로이드 스튜디오 내에서 제공하는 기본 클립아트나, 웹에 있는 아이콘 사이트에서는 적합한 아이콘을 찾기 힘들었습니다.
따로 제작해서 업로드 하겠습니다.

**Comment by kiw331** [comment]
아이콘 추가 완료
unimarket-app/android/app/src/main/res/drawable-v24/app_icon_v1.png
