### ISSUE TITLE
통신 테스트 한번 해보는게 좋을것 같습니다.

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#65]
제가 혼자서 레트로핏2와 플라스크를 연결하여서 통신을 하려고 보니 오류가 계속 나는데 어플을 제가 잘 모르기때문에 테스트 서버를 제가 열테니까 한번 테스트를 해보는 것이 좋을것 같습니다.

**Comment by kiw331** [comment]
Retrofit2 이용해서 GET 요청 테스트 완료
