### ISSUE TITLE
어플 기본 UI 구성

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#7]
먼저 유니마켓 앱 기본 UI를 제작하려 합니다.
저희가 3주차 때 했던 초기구상은 메인화면에서만 갱신된 매물을 확인하고, 검색탭에서 모니터링해서 알림을 받을
조건을 한꺼번에 설정하는 거였습니다.

다만 이렇게 할 경우 메인 화면에서 갱신된 물품을 나타낼 공간이 협소해 보이고, 그렇다고 메인화면의 검색UI 역시 검색탭과 중복되는 기능이라 필수적이라 보기 어려울거 같습니다.

그래서 검색탭은 그대로 두되, **메인화면탭 대신 별도의 매물 알림과 필터를 위한 탭을 만들고
거기에 추가로 설정 탭을 하나 더 만들어 지역설정,  알림설정(소리,진동..), 버전/업데이트 명시 등의 부과적인 기능을 넣고자 하는데** 
다른 의견 있으시면 코멘트 달아주세요.

**Comment by stoneTiger0912** [comment]
괜찮은 것 같습니다.

**Comment by kiw331** [comment]
그럼 이대로 제작해서PR보내겠습니다.

**Comment by jinbong-yeom** [comment]
저도 좋습니다
