### ISSUE TITLE
어플 폰트 정하기

### ISSUE THREAD

**Issue by kiw331** [jinbong-yeom/Uni_Market#70]
UI 개선 사항에서 의견을 받아 저희 어플에 적용될 폰트를 정하려 합니다 2개로 추려왔는데 괜찮은 쪽 골라주시거나 다른 폰트 추천해주세요

**Comment by kiw331** [comment]
## 2. 주아체
![주아](https://user-images.githubusercontent.com/100690081/205303326-72889aa4-9c70-4434-80e3-c1eb045d5fd8.PNG)

**Comment by stoneTiger0912** [comment]
후자가 나을듯합니다.

**Comment by kiw331** [comment]
우선 주아체로 적용 하겠습니다.
