### ISSUE TITLE
크롤링한 데이터 저장 공간 정하기

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#8]
크롤링한 데이터의 url 및 데이터만 참조하는 방식으로 하려고 하는데 csv파일에 저장 또는 데이터베이스(아마 mysql 이나 오라클 예정)에 하려고 합니다. csv파일이 더 쉽고 하기 좋지만 용량이 많이 차지하고 반대로 데이터베이스는 어렵지만 용량을 많이 차지 않는데 어떤 방식으로 할까요?

**Comment by kiw331** [comment]
파이썬 라이브러리를 사용한 csv파일 처리관련 예제가 많이 나와있는 걸로 알고 있습니다.
당장 다수의 사용자를 기대하고 개발하는 단계는 아닌 만큼 우선 csv형식으로 가되, 
나중에 처리속도와 같은 문제가 생기면 바꾸는 방식으로 하면 어떨까요

**Comment by jinbong-yeom** [comment]
알아본 바로는 크롤링한 데이터를 지속적으로 관리하기에는 몽고db가 좋아보입니다.

**Comment by stoneTiger0912** [comment]
> 알아본 바로는 크롤링한 데이터를 지속적으로 관리하기에는 몽고db가 좋아보입니다.

그럼 몽고db로 하겠습니다.
