### ISSUE TITLE
firebase 연동 테스트 성공적으로 연결하였습니다.

### ISSUE THREAD

**Issue by stoneTiger0912** [jinbong-yeom/Uni_Market#85]
<img width="343" alt="스크린샷 2022-12-04 오전 3 25 41" src="https://user-images.githubusercontent.com/91014308/205456154-01ee5164-8a02-43b3-9b4a-03f4778828a8.png">

이제 적용만 하면되겠네요

**Comment by stoneTiger0912** [comment]
대신 백그라운드에서만 나오게 되네요.. 일단 백그라운드에서만 할까요?

**Comment by jinbong-yeom** [comment]
> 대신 백그라운드에서만 나오게 되네요.. 일단 백그라운드에서만 할까요?

알겟습니다.

**Comment by stoneTiger0912** [comment]
그러면 진행하겠습니다
